# Generated by Django 3.1 on 2020-12-20 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0005_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoActividades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('orden', models.IntegerField()),
                ('nombre', models.CharField(max_length=250)),
                ('direccionURL', models.CharField(max_length=1028)),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogos.curso')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
