# Generated by Django 3.1 on 2021-01-03 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0006_videoactividades'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videoactividades',
            options={'ordering': ['orden', 'nombre']},
        ),
    ]
