# Generated by Django 3.1 on 2021-01-05 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0007_auto_20210103_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoactividades',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.curso'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inciso', models.CharField(max_length=1)),
                ('pregunta', models.CharField(max_length=255)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.curso')),
            ],
            options={
                'ordering': ['inciso'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion', models.CharField(max_length=100)),
                ('es_correcta', models.BooleanField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.question')),
            ],
        ),
    ]
