# Generated by Django 3.1 on 2021-01-14 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0008_auto_20210105_0524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-es_correcta']},
        ),
    ]
