# Generated by Django 3.1 on 2021-01-18 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0009_auto_20210114_0414'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioEscuela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.IntegerField()),
                ('municipio', models.IntegerField()),
                ('escuela', models.IntegerField()),
            ],
        ),
    ]
