# Generated by Django 3.1 on 2021-01-30 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0010_usuarioescuela'),
    ]

    operations = [
        migrations.CreateModel(
            name='MisCursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.IntegerField()),
                ('fecha', models.DateField()),
                ('estatus', models.CharField(max_length=255)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.curso')),
            ],
        ),
    ]
